export interface UserInfo {
  first: string;
  last: string;
  dob: string;
  ssn: string;
  address: string;
  city: string;
  state: string;
  zip: string;
}

export type ImpactLevel = 'High' | 'Medium' | 'Low' | 'Positive';
export type PriorityLevel = 'High' | 'Medium' | 'Low';

export interface CreditScore {
  bureau: string;
  score: number | null;
  rating: string;
}

export interface NegativeItem {
  priority: PriorityLevel;
  creditor: string;
  accountNumber: string;
  type: string;
  balance: string;
  status: string;
  dateReported: string;
  reasons: string[];
  impact: PriorityLevel;
  impactPoints: string;
  laws: string[];
  recommendedAction: string;
  /** Which bureaus actually report this item — only the ones present in the report */
  bureaus: string[];
}

export interface ActionItem {
  title: string;
  description: string;
  impact: ImpactLevel;
}

export interface Bureau {
  key: string;
  name: string;
  color: string;
  abbr: string;
  addr: string;
}

export interface AnalysisResult {
  /** Stamped server-side after AI response — not generated by the AI */
  completedAt: string;
  summary: string;
  scores: CreditScore[];
  overall: {
    rating: string;
    /** 0–100, drives the donut chart */
    health: number;
    summary: string;
  };
  strengths: string[];
  weaknesses: string[];
  negativeItems: NegativeItem[];
  actionPlan: ActionItem[];
  stats: {
    totalAccounts: number;
    negativeItemCount: number;
    latePayments: number;
    hardInquiries: number;
    /** e.g. "18%" */
    utilization: string;
    /** e.g. "50–120" */
    estimatedImprovement: string;
  };
  disputeLetters: {
    bureau: string;
    body: string;
  }[];
}
